apiVersion: v1
data:
  prometheus.yml: "# my global config\nglobal:\n  scrape_interval: 120s \n  evaluation_interval:
    60s \n  # scrape_timeout is set to the global default (10s).\n\n# Alertmanager
    configuration\n#alerting:\n#  alertmanagers:\n#    - static_configs:\n#        -
    targets:\n          # - alertmanager:9093\n\n# Load rules once and periodically
    evaluate them according to the global 'evaluation_interval'.\nrule_files:\n  #
    - \"first_rules.yml\"\n  # - \"second_rules.yml\"\n\n# A scrape configuration
    containing exactly one endpoint to scrape:\n# Here it's Prometheus itself.\nscrape_configs:\n
    \ # The job name is added as a label `job=<job_name>` to any timeseries scraped
    from this config.\n  - job_name: \"prometheus\"\n\n    # metrics_path defaults
    to '/metrics'\n    # scheme defaults to 'http'.\n\n    static_configs:\n      -
    targets: [\"localhost:9090\"]\n  - job_name: \"weather\"\n    # mertics_path:
    \"/api/weather/zurich\"\n    static_configs:\n      - targets: [\"unit8-prep:8080\"]\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-prometheus
