
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: unit8-prep
  name: unit8-prep
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: unit8-prep
  type: LoadBalancer
status:
  loadBalancer: {}