name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    env:
      IMGTAG: sasfeszek/unit8:${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMGTAG }}
          build-args: OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }}
      - uses: actions/checkout@v2
      -
        name: Variable injection
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'deployment/nginx/deployment.yaml'
        env:
          spec.template.spec.containers.0.image: ${{ env.IMGTAG }}
      - 
        name: Deploy deployment to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: apply -f deployment/nginx -n prometheus
      - 
        name: Deploy deployment to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: apply -f deployment/prometheus -n prometheus

